kind: Deployment
apiVersion: apps/v1
metadata:
   name: testing
   labels:
    site: test
spec:
   replicas: 1
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     site: test
   template:
     metadata:
       name: testpod1
       labels:
         site: test
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80